### ISSUE TITLE
Update OpenShift resources in Traction Test to the “load test” levels in Sandbox and revert Sandbox to pre-Load Test levels

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP-DevOps#153]
We will be using Test for load testing vs. Sandbox. Please update the resources in Test to match what we raised Sandbox to when we started load testing, and revert Sandbox to the pre-load testing levels.

**Comment by WadeBarnes** [comment]
Aaca-py instances have been configured with:
```
  - resources:
      limits:
        cpu: '1'
        memory: 1600Mi
      requests:
        cpu: 200m
        memory: 820Mi
```

**Comment by i5okie** [comment]
CrunchyDB PostgreSQL Cluster has been updated with:
```
resources:
  limits:
    cpu: '2'
    memory: 4000Mi
  requests:
    cpu: 200m
    memory: 820Mi
```
