### ISSUE TITLE
Deploy Traction sandbox instance

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#99]
Deploy Traction sandbox instance with auto-provisioning flags set to `true` - connect with @esune and @WadeBarnes to define where to deploy it to.
Decommission Anoncreds instance.

Pre-Requisites:
- [x] Install Helm on the local development machine
- [x] Complete the Helm getting started guide: https://helm.sh/docs/chart_template_guide/getting_started
- [x] Familiarize with the documentation for the Traction Helm charts: https://github.com/bcgov/traction/tree/main/charts

Acceptance Criteria:
- [x] New instance of Traction and Tenant UI are deployed and work, with self-provisioning turned on in `bc0192-test`
- [x] The custom values files for this specific deployment should be saved to https://github.com/bcgov/trust-over-ip-configurations/tree/main/helm-values
- [x] Anoncreds Traction instance is uninstalled (both Helm chart and leftover artifacts) from namespace `a99fd4-test`

**Comment by rajpalc7** [comment]
https://tenant-ui-sandbox-dev.apps.silver.devops.gov.bc.ca  is the URL when tenant-ui sandbox was deployed. I didnt get any URL for traction-sandbox.

**Comment by esune** [comment]
> https://tenant-ui-sandbox-dev.apps.silver.devops.gov.bc.ca is the URL when tenant-ui sandbox was deployed. I didnt get any URL for traction-sandbox.

Thank you @rajpalc7. The back-end service `traction-sandbox` will not have public URLs exposed so that is expected.

Could you please try validating that the services work as expected too? You will need to:
- Create a new tenant request in the Tenant UI (https://tenant-ui-sandbox-dev.apps.silver.devops.gov.bc.ca)
- Once the request is submitted, approve it from the `innkeeper` view (https://tenant-ui-sandbox-dev.apps.silver.devops.gov.bc.ca/innkeeper). Username/password for the innkeeper will be in the `traction-sandbox-acapy-plugin-innkeeper` secret that was created when you deployed the solution.
- From the innkeeper view, approve the new reservation
- Check-in usign the Tenant UI with the newly approved reservation to create a tenant and get your wallet id and wallet key
- Sign-in to the Tenant UI using the credentials you just obtained

This will confirm the basic functionality is working as expected, we can further check other pieces of functionality later on as-needed.

**Comment by rajpalc7** [comment]
Thanks @esune - I tried using the secrets from here https://console.apps.silver.devops.gov.bc.ca/k8s/ns/bc0192-test/secrets/traction-sandbox-acapy-plugin-innkeeper   but i seem to get network error because the pod is down. I suspect there is some issue with https://github.com/bcgov/traction/blob/c5e3a175fd7afd03e00df8ae79c83110619277ee/deploy/traction/values-development.yaml  file

**Comment by rajpalc7** [comment]
Thanks @esune - I tried using the innkeeper credentials from https://console.apps.silver.devops.gov.bc.ca/k8s/ns/bc0192-test/secrets/traction-sandbox-acapy-plugin-innkeeper but got a 404 error.

**Comment by rajpalc7** [comment]
![image](https://github.com/bcgov/DITP-DevOps/assets/98990802/fb459ac2-3961-44ca-a4d8-31d7b4de7584)

**Comment by rajpalc7** [comment]
![image](https://github.com/bcgov/DITP-DevOps/assets/98990802/9024e901-5e47-4918-be67-06c05bc0f14e)

**Comment by esune** [comment]
> Its asking me to wait for 3-5 business days and not auto-approving
> 

That likely means that the pods have not restarted and did not pick-up the new settings, otherwise it should provide you with the wallet id/key pair to sign-in right away. Try checking that and submitting a new tenant request after the pods are running using the latest configuration.

**Comment by rajpalc7** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblJ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6d276561aea19bef290537cb4d4a2e2773452434/image.png)

**Comment by rajpalc7** [comment]
I was able to fix the issue. Auto-approving is working as expected now

**Comment by esune** [comment]
Thank you @rajpalc7. One extra tweak is needed: can you please remove the `-dev` suffix from the URL? There will only ever be one sandbox environment, so it doesn't make sense to have the `-dev` nameplate on this deployment.

Additionally, we will need the configuration file(s) you used to deploy this instance PR'd to https://github.com/bcgov/trust-over-ip-configurations - please link the PR here when ready.

I smoke-tested by creating a tenant for myself and connecting to the endorser and everything seems to work as expected.

**Comment by rajpalc7** [comment]
```
ingressSuffix: apps.silver.devops.gov.bc.ca
image:
  tag: "0.2.14"
  pullPolicy: Always
traction:
  pluginInnkeeper:
    existingSecret: traction-acapy-plugin-innkeeper
    generated: true
  apiEndpoint: https://traction-sandbox-tenant-proxy-dev.apps.silver.devops.gov.bc.ca 
  tenantProxyEndpoint: https://traction-sandbox-tenant-proxy-dev.apps.silver.devops.gov.bc.ca
  reservation:
    expiry_minutes: 2880
    auto_approve:  true
    auto_issuer: true
  resources:
    limits:
      cpu: 200m
      memory: 820Mi
    requests:
      cpu: 120m
      memory: 400Mi
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector:
        network.openshift.io/policy-group: ingress
oidc:
  active: false
  showInnkeeperAdminLogin: false
  showWritableComponents: false
  authority: https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm
  jwksUri: https://dev.loginproxy.gov.bc.ca/auth/realms/digitaltrust-nrm/protocol/openid-connect/certs
ariesDetails:
  ledgerDescription: "bcovrin-test"
smtp:
  server: apps.smtp.gov.bc.ca
  port: 25
  senderAddress: DoNotReplyTractionSandbox@gov.bc.ca
  innkeeperInbox: "lucas.o'neil@gov.bc.ca,emiliano.sune@quartech.com"
resources:
  limits:
    cpu: 400m
    memory: 1600Mi
  requests:
    cpu: 200m
    memory: 820Mi
ingress:
  annotations:
    route.openshift.io/termination: edge
networkPolicy:
  enabled: true
  ingress:
    enabled: true
    namespaceSelector:
      network.openshift.io/policy-group: ingress
      ```
